"""Init 2

Revision ID: 52871a40ff8c
Revises: 185c56f6dec8
Create Date: 2024-05-13 19:58:51.112656

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '52871a40ff8c'
down_revision = '185c56f6dec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_referral_link_association',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['referral_link_id'], ['referral_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'referral_link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_referral_link_association')
    # ### end Alembic commands ###
