"""Init

Revision ID: a366d0ec2e9a
Revises: 
Create Date: 2024-04-19 15:48:56.483781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a366d0ec2e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referal_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('buys_cnt', sa.Integer(), nullable=False),
    sa.Column('buys_sum', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('bot_link', sa.String(), nullable=False),
    sa.Column('site_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_link'),
    sa.UniqueConstraint('site_link')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('gemini_daily_limit', sa.Integer(), nullable=False),
    sa.Column('kandinsky_daily_limit', sa.Integer(), nullable=False),
    sa.Column('sd_daily_limit', sa.Integer(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('main_tariff_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_extra', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('main_tariff_id')
    )
    op.create_table('text_generation_roles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users_admin',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hash_password', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('gemini_daily_limit', sa.Integer(), nullable=False),
    sa.Column('kandinsky_daily_limit', sa.Integer(), nullable=False),
    sa.Column('sd_daily_limit', sa.Integer(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('txt_model', sa.String(), nullable=False),
    sa.Column('txt_model_role_id', sa.BigInteger(), nullable=True),
    sa.Column('img_model', sa.String(), nullable=False),
    sa.Column('tts_mode', sa.String(), nullable=False),
    sa.Column('text_session_id', sa.BigInteger(), nullable=True),
    sa.Column('update_daily_limits_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tariff_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('mother_invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_tries', sa.Integer(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('first_payment', sa.Boolean(), nullable=False),
    sa.Column('referal_link_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referal_link_id'], ['referal_links.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['text_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['txt_model_role_id'], ['text_generation_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_queries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('mother_invoice_id', sa.Integer(), nullable=True),
    sa.Column('tariff_id', sa.BigInteger(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('attention', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_queries')
    op.drop_table('text_queries')
    op.drop_table('service_queries')
    op.drop_table('refunds')
    op.drop_table('invoices')
    op.drop_table('image_queries')
    op.drop_table('users')
    op.drop_table('users_admin')
    op.drop_table('text_generation_roles')
    op.drop_table('tariffs')
    op.drop_table('sessions')
    op.drop_table('referal_links')
    # ### end Alembic commands ###
