"""Init

Revision ID: 185c56f6dec8
Revises: 
Create Date: 2024-05-13 19:58:04.361604

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '185c56f6dec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('Всего пользователей', sa.Integer(), nullable=False),
    sa.Column('Пользователей с реф. ссылок', sa.Integer(), nullable=False),
    sa.Column('Новых пользователей', sa.Integer(), nullable=False),
    sa.Column('Новых пользователей с реф. ссылок', sa.Integer(), nullable=False),
    sa.Column('Новых пользователей с поиска', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов ChatGPT 3', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов ChatGPT 4', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов YaGPT', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов YaGPT Lite', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов Gemini', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов Claude', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов StableDiffusion', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов DALL-E-2', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов DALL-E-3', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов Midjourney', sa.Integer(), nullable=False),
    sa.Column('Кол-во запросов Kandinsky', sa.Integer(), nullable=False),
    sa.Column('Кол-во генераций текст в видео', sa.Integer(), nullable=False),
    sa.Column('Кол-во генераций картинка в видео', sa.Integer(), nullable=False),
    sa.Column('Кол-во удаления фона с видео', sa.Integer(), nullable=False),
    sa.Column('Кол-во генераций видео в мульт', sa.Integer(), nullable=False),
    sa.Column('Кол-во генераций PicaArt', sa.Integer(), nullable=False),
    sa.Column('Кол-во генераций дипломов', sa.Integer(), nullable=False),
    sa.Column('Кол-во рерайта', sa.Integer(), nullable=False),
    sa.Column('Кол-во решений по фото', sa.Integer(), nullable=False),
    sa.Column('Кол-во генераций статей', sa.Integer(), nullable=False),
    sa.Column('Кол-во озвучек', sa.Integer(), nullable=False),
    sa.Column('Кол-во речь в текст', sa.Integer(), nullable=False),
    sa.Column('Кол-во удаления фона с картинок', sa.Integer(), nullable=False),
    sa.Column('Кол-во премиум пользователей', sa.Integer(), nullable=False),
    sa.Column('Кол-во новых оплат премиума', sa.Integer(), nullable=False),
    sa.Column('Сумма новых оплат премиума', sa.Integer(), nullable=False),
    sa.Column('Кол-во новых оплат токенов', sa.Integer(), nullable=False),
    sa.Column('Сумма новых оплат токенов', sa.Integer(), nullable=False),
    sa.Column('Кол-во новых оплат', sa.Integer(), nullable=False),
    sa.Column('Сумма новых оплат', sa.Integer(), nullable=False),
    sa.Column('Средний чек', sa.Integer(), nullable=False),
    sa.Column('Кол-во покупок триала', sa.Integer(), nullable=False),
    sa.Column('Кол-во покупок по тарифам', sa.JSON(), nullable=False),
    sa.Column('Кол-во продлений', sa.Integer(), nullable=False),
    sa.Column('Дата', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('chatgpt_daily_limit', sa.Integer(), nullable=True),
    sa.Column('gemini_daily_limit', sa.Integer(), nullable=False),
    sa.Column('kandinsky_daily_limit', sa.Integer(), nullable=False),
    sa.Column('sd_daily_limit', sa.Integer(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('main_tariff_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_extra', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('main_tariff_id')
    )
    op.create_table('text_generation_roles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users_admin',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hash_password', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('chatgpt_daily_limit', sa.Integer(), nullable=True),
    sa.Column('gemini_daily_limit', sa.Integer(), nullable=False),
    sa.Column('kandinsky_daily_limit', sa.Integer(), nullable=False),
    sa.Column('sd_daily_limit', sa.Integer(), nullable=False),
    sa.Column('token_balance', sa.Integer(), nullable=False),
    sa.Column('txt_model', sa.String(), nullable=False),
    sa.Column('txt_model_role_id', sa.BigInteger(), nullable=True),
    sa.Column('img_model', sa.String(), nullable=False),
    sa.Column('tts_mode', sa.String(), nullable=False),
    sa.Column('text_session_id', sa.BigInteger(), nullable=True),
    sa.Column('update_daily_limits_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tariff_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('mother_invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_tries', sa.Integer(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('first_payment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['text_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['txt_model_role_id'], ['text_generation_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_queries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('mother_invoice_id', sa.Integer(), nullable=True),
    sa.Column('tariff_id', sa.BigInteger(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('buys_cnt', sa.Integer(), nullable=False),
    sa.Column('buys_sum', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('bot_link', sa.String(), nullable=False),
    sa.Column('site_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_link'),
    sa.UniqueConstraint('site_link')
    )
    op.create_table('refunds',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('attention', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_queries',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_queries')
    op.drop_table('text_queries')
    op.drop_table('service_queries')
    op.drop_table('refunds')
    op.drop_table('referral_links')
    op.drop_table('invoices')
    op.drop_table('image_queries')
    op.drop_table('users')
    op.drop_table('users_admin')
    op.drop_table('text_generation_roles')
    op.drop_table('tariffs')
    op.drop_table('sessions')
    op.drop_table('reports')
    # ### end Alembic commands ###
