"""null user in queries

Revision ID: f6b6b70d4238
Revises: f87bfbce9771
Create Date: 2024-05-10 11:48:23.711347

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f6b6b70d4238'
down_revision = 'f87bfbce9771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)

    with op.batch_alter_table('service_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)

    with op.batch_alter_table('text_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)

    with op.batch_alter_table('video_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)

    with op.batch_alter_table('text_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)

    with op.batch_alter_table('service_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)

    with op.batch_alter_table('image_queries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BIGINT(),
                              nullable=False)

    # ### end Alembic commands ###
