SPEAKERS = {
    "Обычные голоса": [
        "aidar",
        "baya",
        "eugene",
        "kseniya",
        "xenia",
    ],
    "Atomic Heart": [
        "babazina",
        "hraz",
        "p3",
        "tereshkova",
    ],
    "Skyrim": {
        "Уникальные": [
            "ancano",
            "astrid",
            "aventus",
            "brynjolf",
            "cicero",
            "delphine",
            "delvin",
            "elenwen",
            "emperor",
            "esbern",
            "felldir",
            "gormlaith",
            "hadvar",
            "hakon",
            "hermaeus",
            "karliah",
            "kodlak",
            "maven",
            "mercer",
            "mirabelle",
            "motierre",
            "nazir",
            "tsun",
            "tullius",
            "ulfric",
            "vex",
        ],
        "Драконы": [
            "alduin",
            "dragon",
            "odahviing",
            "paarthurnax",
        ],
        "Мужские NPC": [
            "arngeir",
            "ebony",
            "eorlund",
            "falion",
            "farengar",
            "farkas",
            "festus",
            "m_argo",
            "m_bandit",
            "m_citizen",
            "m_commander",
            "m_commoner",
            "m_coward",
            "m_darkelf",
            "m_drunk",
            "m_forsworn",
            "m_guard",
            "m_haughty",
            "m_khajiit",
            "m_nord",
            "m_orc",
            "m_soldier",
            "malkoran",
            "nazeem",
            "sven",
            "tolfdir",
        ],
        "Монстры": [
            "barbas",
            "dremora",
            "hagraven",
        ],
        "Женские NPC": [
            "elisif",
            "f_argo",
            "f_commander",
            "f_commoner",
            "f_coward",
            "f_darkelf",
            "f_haughty",
            "f_khajiit",
            "f_nord",
            "f_orc",
            "f_shrill",
            "f_sultry",
            "grelka",
            "grelod",
            "lydia",
            "olava",
        ],
        "Дети": [
            "f_child",
            "m_child",
        ],
    },
    "WarCraft 3": {
        "Популярные": [
            "acolyte",
            "anubarak",
            "archmage",
            "arthas",
            "chen",
            "furion",
            "grom",
            "grunt",
            "illidan",
            "kelthuzad",
            "rexxar",
            "thrall",
        ],
        "Альянс": [
            "admiral",
            "archmage",
            "breaker",
            "captain",
            "elf_eng",
            "footman",
            "garithos",
            "jaina",
            "kael",
            "medivh",
            "muradin",
            "narrator",
            "peasant",
            "villagerm",
            "priest",
            "rifleman",
            "sorceress",
            "sylvanas_w",
            "uther",
            "villagerm",
        ],
        "Орда": [
            "alchemist",
            "cairne",
            "chen",
            "grom",
            "grunt",
            "hh",
            "peon",
            "rexxar",
            "thrall",
            "voljin",
        ],
        "Нежить": [
            "acolyte",
            "anubarak",
            "archimonde",
            "arthas",
            "dread_bm",
            "dread_t",
            "kelthuzad",
            "mannoroth",
            "sylvanas",
        ],
        "Ночные эльфы": [
            "dryad",
            "furion",
            "huntress",
            "illidan",
            "illidan_f",
            "keeper",
            "ladyvashj",
            "maiev",
            "naga_m",
            "naga_rg",
            "naisha",
            "satyr",
            "tyrande",
        ],
    },
    "Half-Life 2": [
        "alyx",
        "barney",
        "breen",
        "father",
        "gman",
        "gman_e2",
        "kleiner",
        "overwatch",
        "vort",
        "vort_e2",
    ],
    "StarCraft": [
        "hanson",
        "hill",
        "kerrigan",
        "raynor",
        "stetmann",
        "swann",
        "tosh",
        "tychus",
        "valerian",
    ],
    "Portal 2": [
        "glados",
        "wheatley",
    ],
    "STALKER": [
        "bandit",
        "barman",
    ],
    "DotA 2": [
        "announcer",
        "antimage",
        "batrider",
        "bloodseeker",
        "bounty",
        "bristle",
        "clockwerk",
        "doom",
        "earth",
        "gyro",
        "huskar",
        "juggernaut",
        "kotl",
        "kunkka",
        "lancer",
        "lina",
        "luna",
        "meepo",
        "mortred",
        "omni",
        "pudge",
        "queen",
        "ranger",
        "riki",
        "shaker",
        "skywrath",
        "sniper",
        "storm",
        "templar",
        "tide",
        "treant",
        "tusk",
        "windranger",
        "witchdoctor",
        "wraith",
    ],
    "LOL": {
        "Популярные": [
            "azir",
            "evelynn",
            "pantheon",
            "yuumi",
        ],
        "Mage": [
            "ahri",
            "anivia",
            "azir",
            "cassiopeia",
            "lissandra",
            "ryze",
            "swain",
            "taliyah",
        ],
        "Marksman": [
            "akshan",
            "draven",
            "graves",
            "quinn",
            "samira",
            "tristana",
        ],
        "Tank": [
            "braum",
            "ksante",
            "nunu",
            "ornn",
            "sejuani",
            "zac",
        ],
        "Fighter": [
            "camille",
            "darius",
            "dr_mundo",
            "garen",
            "hecarim",
            "kayle",
            "olaf_lol",
            "sett",
            "shyvana",
            "trundle",
            "udyr",
            "vi",
            "volibear",
        ],
        "Slayer": [
            "ekko",
            "fizz",
            "katarina",
            "kled",
            "nilah",
            "qiyana",
            "riven",
            "sylas",
            "talon",
            "tryndamere",
            "yone",
        ],
        "Specialist": [
            "gangplank",
        ],
        "Controller": [
            "janna",
            "karma",
            "nami",
            "neeko",
            "rakan",
            "renata_glasc",
            "senna",
            "taric",
            "zyra",
        ],
    },
    "Fallout 1 & 2": {
        "Популярные": [
            "dick",
            "dornan",
            "elder",
            "frank",
            "hakunin",
            "harold",
            "marcus",
            "master",
            "officer",
            "overseer",
        ],
        "Fallout 1": [
            "aradesh",
            "cabbot",
            "decker",
            "dick",
            "gizmo",
            "harris",
            "harry",
            "jain",
            "killian",
            "laura",
            "lieutenant",
            "loxley",
            "master",
            "maxson",
            "morpheus",
            "nicole",
            "overseer",
            "rhombus",
            "set",
            "tandi",
            "vree",
        ],
        "Fallout 2": [
            "dick",
            "dornan",
            "elder",
            "frank",
            "harold",
            "marcus",
            "myron",
            "officer",
            "sulik",
        ],
    },
    "Postal 2": [
        "dude",
    ],
    "Team Fortress 2": [
        "demoman",
        "engineer",
        "heavy",
        "medic",
        "scout",
        "sniper_tf",
        "soldier",
        "spy",
    ],
    "Hearthstone": {
        "Нейтральные": [
            "akazamzarak",
            "aranna",
            "arwyn",
            "azalina",
            "bob",
            "brann",
            "cache",
            "deathwhisper",
            "dendrologist",
            "dr_boom",
            "draan",
            "elise",
            "eudora",
            "goya",
            "greymane",
            "hancho",
            "innkeeper",
            "kazakus",
            "malchezaar",
            "moroes",
            "omnotron",
            "omu",
            "pollark",
            "reno",
            "rikkar",
            "stelina",
            "togwaggle",
            "vargoth",
            "wagtoggle",
        ],
        "Паладин": [
            "aki",
            "bolan",
            "george",
            "glowtron",
            "illidara",
            "rasil",
            "tarkus",
            "timothy",
            "turalyon",
            "valdera",
            "yrel_hs",
        ],
        "Друид": [
            "ammunae",
            "anarii",
            "applebough",
            "edra",
            "floop",
            "loti",
            "malfurion",
            "splintergraft",
            "squeamlish",
            "tala",
            "zenda",
        ],
        "Жрец": [
            "anduin",
            "baechao",
            "haro",
            "illucia",
            "jythiros",
            "lazul",
            "nici",
            "oshi",
            "talanji",
            "tyrande_hs",
            "zoie",
        ],
        "Охотник": [
            "arha",
            "avozu",
            "belnaara",
            "cardish",
            "draemus",
            "flark",
            "ivan",
            "lunara",
            "putricide",
            "shaw",
            "slate",
            "smiggs",
        ],
        "Воин": [
            "awilo",
            "biggs",
            "chu",
            "dagg",
            "dovo",
            "hannigan",
            "ilza",
            "kasa",
            "kizi",
            "kyriss",
            "saurfang",
            "tierra",
        ],
        "Шаман": [
            "brukan",
            "disidra",
            "fireheart",
            "hagatha",
            "hesutu",
            "inara",
            "lady_vashj",
            "ozara",
            "rastakhan",
            "rhogi",
            "siamat",
            "thunderking",
            "zentimo",
            "zibb",
        ],
        "Разбойник": [
            "albin",
            "candlebeard",
            "gallywix",
            "gnomenapper",
            "hooktusk",
            "lilian",
            "linzi",
            "maiev_hs",
            "myra",
            "ol_toomba",
            "taskmaster",
            "thrud",
            "valeera_hs",
        ],
        "Чернокнижник": [
            "cravitz",
            "dr_sezavo",
            "jeklik",
            "jolene",
            "karastamper",
            "kazamon",
            "lanathel",
            "marei",
            "oxana",
            "sthara",
            "tekahn",
            "tekahn_boss",
            "willow",
        ],
        "Маг": [
            "isiset",
            "kalec",
            "katrana",
            "khadgar",
            "lilayell",
            "malacrass",
            "mozaki",
            "norroa",
            "robold",
            "sinclari",
            "stargazer",
            "wendy",
            "whirt",
            "xurios",
        ],
    },
    "HotS": {
        "HotS": [
            "default",
            "orphea",
        ],
        "Starcraft": [
            "abathur",
            "alarak",
            "kerrigan_h",
            "mechatassadar",
            "mira",
        ],
        "Announcer": [
            "adjutant",
            "athena",
            "blackheart",
            "drekthar",
            "gardensdayannouncer",
            "ladyofthorns",
            "necromancer",
            "toy18",
            "volskaya",
        ],
        "Overwatch": [
            "ana",
            "dva",
            "lucio",
            "zarya",
        ],
        "Warcraft": [
            "anduin",
            "chromie",
            "greymane_h",
            "malfurion",
            "rehgar",
            "samuro",
            "valeera",
            "varian",
            "whitemane",
            "yrel",
            "zuljin",
        ],
        "Diablo": [
            "angel",
            "barbarian",
            "crusader",
            "deckard",
            "demon",
            "demonhunter",
            "tyrael",
            "witchdoctor_h",
        ],
        "Lost Vikings": [
            "erik",
            "olaf",
        ],
    },
    "Metro": {
        "Зима": [
            "bandit2",
            "bandit3",
            "bridger1",
            "bridger2",
            "bridger3",
        ],
        "Лето": [
            "slave1",
            "slave2",
            "slave3",
            "tribal1",
            "tribal3",
        ],
        "Лес": [
            "forest1",
            "forest2",
            "forest3",
        ],
        "Напарники": [
            "krest",
            "miller",
        ],
        "Другое": [
            "cannibal2",
            "cannibal3",
            "merc1",
            "merc2",
        ],
    },
    "Overwatch": {
        "Support": [
            "ana",
            "baptiste",
            "brigitte",
            "kiriko",
            "lucio_ov",
            "mercy",
            "moira",
            "training_robot",
            "zenyatta",
        ],
        "Damage": [
            "ashe",
            "cassidy",
            "echo",
            "genji",
            "hanzo",
            "junkrat",
            "pharah",
            "reaper",
            "sojourn",
            "soldier_76",
            "sombra",
            "symmetra",
            "tracer",
            "widowmaker",
        ],
        "Tank": [
            "doomfist",
            "dva_ov",
            "junker_queen",
            "roadhog",
            "sigma",
            "winston",
            "zarya",
        ],
    },
    "Rita": [
        "rita",
    ],
    "Evil Islands": [
        "zak",
    ],
    "Valorant": [
        "brimstone",
        "harbor",
        "sage",
        "sova",
    ],
}
